In [1]:
import numpy as np

El array es el principal objeto de la librería. Representa datos de manera esttructurada y se puede acceder a ellos a trevés del indexado (sus números de índice) a un dato específico ó un grupo de muchos datos

In [2]:
lista = [1, 2, 3, 4, 5, 6]
lista

[1, 2, 3, 4, 5, 6]

definimos un array usando `np.array(lista)` 
* el argumento es la lista anterior

In [3]:
lista_array = np.array(lista)

In [5]:
print(type(lista_array), type(lista))

<class 'numpy.ndarray'> <class 'list'>


Dimensiones de arrays
* **vectorr**: array de una dimensión 
* **matriz**: array con dos dimensiones
* **tensor**: array de tres dimensiones

In [45]:
#1 dim (Escalar)
arr_1dim = np.array([1, 2, 3, 4]) #  ó si no np.array(lista)

# 2 dim (matriz)
arr_2dim = np.array([
                      [1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]
                    ])

# 3 dim (tensor)
arr_3dim = np.array([
                      [
                          [1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],
                          [1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],
                          [1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]
                      ]
                    ])

In [46]:
print(f' una dimensión: {arr_1dim}\n **** \n dos dimensiones:\n{arr_2dim}\n **** \n tres dimensiones: \n{arr_3dim}')

 una dimensión: [1 2 3 4]
 **** 
 dos dimensiones:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 **** 
 tres dimensiones: 
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


### indexing
Podemos acceder a cualquier elemento del array incodándolo por su posición en el índice: `array[0]`
* Recordar que los índices empiezan por $0$


In [17]:
arr_1dim[1]

2

sumar elementos de un array invocándolos por su número de índice

# Respecto a la suma de elementos de una matriz
* el primer elemento que colocamos representa a las **filas**
* el segundo a las **columnas**

   `arr_matriz[`*filas*`,`*columnas*`]` $\equiv$  `arr_matriz[0,1]`

*Estando operando en una matriz, si colocamos sólo un argumento, estará trayendo todos los elementos de la fila*


In [47]:
#una dimensión
suma_arr = arr_1dim[2] + arr_1dim[3]
suma_matriz = arr_2dim[0,1] + arr_2dim[1,1]

print(f' Suma en una dimensión:   {suma_arr} \n Suma en dos dimensiones: {suma_matriz}')


 Suma en una dimensión:   7 
 Suma en dos dimensiones: 8


Acceder a varios elementos a la vez (matriz) por medio de slices
* *[donde empieza : donde termina : cuántos pasos se darán hacia el siguiente]*

In [62]:
slices_arr = [
               arr_1dim[-3: ],      # acceder a los últimos tres elementos del array
               arr_1dim[-1],        # acceder al último elemento del array
               arr_1dim[-1 : : -2]  # acceder a todos los elementos `: todos : ` empezando del último hacia atrás, de dos en dos
             ]
slices_arr

[array([2, 3, 4]), 4, array([4, 2])]

In [51]:
slices_matriz= [
    arr_2dim[1, :3],    # elementos desde la posición "0" hasta la 3 -1
    arr_2dim[1, 1:],    # elementos desde la posición "1" en adelante
    arr_2dim[1, : :3],  # todos los elementos de la segunda fila, pero cada 3 espacios
    arr_2dim[1, -1],    # el ÚLTIMO elemento de la segunda fila
    arr_2dim[1,-3],     # el tercer último elemento de la segunda fila
    arr_2dim[-1 :],     # acceder a la última fila
    arr_2dim[-2 :]      # acceder a las últimas dos filas
]
slices_matriz

[array([5, 6, 7]),
 array([6, 7, 8]),
 array([5, 8]),
 8,
 6,
 array([[ 9, 10, 11, 12]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])]

Al invocar los elementos por slices, el último elemento no se cuenta

`arr[1: , 0:2]` este slice se lee de la siguiente forma:
  * `1:` segunda fila  en adelante 
  * `, 0:2` desde la primera columna hasta la tercera (sin contar el último)

In [68]:
print(f' {arr_2dim} \n  selección: \n {arr_2dim[1: , 0:2]}')

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 
  selección: 
 [[ 5  6]
 [ 9 10]]
