# Dimensiones de arrays: Scalar, vector,  matriz, tensor

Usando el método `.ndim` podemos ver las dimensiones que tiene una variable que contenga elementos

* **scalar**: $0$ un solo dato o valor (sin dimensiones)
   * `scalar = np.array([1])`\
    \
* **vector**: $r1$ listas de elementos, cada uno separado por comas
    * se miden por columnas, suendo un apor cada elemento `[3,]` $\equiv$ `[columnas, ]`
    * `vector = np.array([1, 2, 3, 4, 5])`\
    \
* **matriz**: $r2$ hojas de cálculo. Conjunto de vectores donde cada fila representa un vector, y cada columna representa a un elemento presente en dicho vector (en este caso fila)
    * se miden por filas (ejemplos) y columnas `[3,2]` $\equiv$ `[filas, columnas]`
    * `matriz = np.array([ [1, 2, 3], [4, 5, 6],[7, 8, 9] ])`\


## tensor
$r3+$ Conjunto de matrices, pueden ser series de tiempo, imágenes
    * respecto a las series de tiempo se refiere a tener una serie de:
      * `[#,#,3]` *= repeticiones* : número de columnas
      * `[#,3,#]` *= columnas*: comportamiento a través del tiempo 
      * `[3,#,#]` *= filas*: número de matrices (ejemplos)


    * se miden por filas, columnas, y cantidad de veces que se repiten: `[3,2,4]` $\equiv$ `[filas, columnas, repeticiones]`
    * `tensor = np.array([`  
        `[ [1, 2, 3], [4, 5, 6], [7, 8, 9] ],`

        `[ [10, 11, 12], [13, 14, 15], [16, 17, 18] ],`
                          
        `[ [19, 20, 21], [22, 23, 24], [25, 26, 92] ]`
                         
        `])` 

### representando una imagen en un tensor
teniendo un tensor de 4 dimensiones (una imagen dividida en canales RGB) sería:
  * número de matrices (ejemplos)
  * filas, columnas
  * canales

así se vería una imagen en un tensor de 4 dimensiones: *(1, altura, ancho, canales de color)*
        
`imagen = np.zeros((1, 256, 256, 3), dtype=np.uint8)`

  * En este ejemplo, la variable "imagen" es un array de cuatro dimensiones con tamaño (1, 256, 256, 3): 
    * `1` El primer índice es 1 ya que solo hay una imagen
    * `256, 256` El segundo y el tercero representan la altura y el ancho de la imagen
    * `3` el último índice representa los tres canales de color (rojo, verde y azul) en formato RGB
    * `dytpe` ayuda a especifica el tipo de dato con el que estaramos trabajando

### representando un video en un tensor
Supongamos que tenemos un video de tamaño 128x128 con 30 fotogramas por segundo, y que cada fotograma está en formato RGB (tres canales de color)

* Creamos un array de cuatro dimensiones de tamaño (fotogramas, altura, ancho, canales de color)

`video = np.zeros((30, 128, 128, 3), dtype=np.uint8)`

En este ejemplo, la variable "video" es un array de cuatro dimensiones con tamaño (30, 128, 128, 3) siendo:
* `30` El primer índice representa el número de fotogramas en el video
* `128, 128` El segundo y el tercero representan la altura y el ancho de cada fotograma
* `3` El último índice representa los tres canales de color (rojo, verde y azul) en formato RGB



In [3]:
import numpy as np

scalar

In [3]:
scalar = np.array([1])
print(f' scalar: {scalar}, dimensiones: {scalar.ndim}')

 scalar: [1], dimensiones: 1


vector

In [4]:
vector = np.array([1, 2, 3, 4])
print(f' vectorr: {vector}, dimensiones: {vector.ndim}')

 vectorr: [1 2 3 4], dimensiones: 1


matriz

In [5]:
matriz = np.array([ [1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9] ])
print(f' matriz: {matriz}\n dimensiones:\n {matriz.ndim}')

 vectorr: [[1 2 3]
 [4 5 6]
 [7 8 9]], dimensiones: 2


tensor

In [7]:
tensor = np.array([
                    [ 
                      [1, 2, 3], 
                      [4, 5, 6],
                      [7, 8, 9],
                    ], 
                    [ 
                      [1, 2, 3], 
                      [4, 5, 6],
                      [7, 8, 9],
                    ],
                    [ 
                      [1, 2, 3], 
                      [4, 5, 6],
                      [7, 8, 9],
                    ]            
                ])
print(f' tensor: \n {tensor}\n dimensiones:\n {tensor.ndim}')

 tensor: 
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
 dimensiones:
 3


# agregar / eliminar dimensiones
Es muy util controlar la cantidad de dimensiones dependiendo de la necesidad de nuestro algoritmo, sobre todo al entrenar modelos de ML

### Agregar  dimensiones

* **indicar** dimensiones al crear un array:
  * para especificar el número de dimensiones que tendrá un array usamos el argumento `array.ndmin= #` dentro de la función `np.array()`\
\
* **aumentar** dimensiones en un array que ya existe: 
  *usamos la función `np.expand_dims()` teniendo como argumentos:
    * el array
    * `axis= #` el número de dimensiones en el eje
       * *axis =0* se agregarán dimensiones en las **filas**
       * *axis =1* se agregarán dimensiones en las **columnas**

 **En python, al interactuar con los ejes:**
   * **$0 \equiv$ filas**
   * **$1 \equiv$ columnas**


In [10]:
# indicar número de dimensiones al crear un array
array_dim = np.array([1, 2, 3], ndmin= 10)
print(f' array: {array_dim}\n número de dimensiones: {array_dim.ndim}')

 array: [[[[[[[[[[1 2 3]]]]]]]]]]
 número de dimensiones: 10


In [28]:
# aumentar dimensiones en un array ya existente
array = np.array([1, 3, 5])
more_dims_row = np.expand_dims(array, axis= 1)  #aumentar dimensiones en columnas
more_dims_col = np.expand_dims(array, axis =0)  #aumentar dimensiones en filas

In [29]:
print(f' array: {array}, dimensiones: {array.ndim}\n ***')
print(f' mismo array agregando una dimensión a nivel columnas: {more_dims_col} , dimensiones: {more_dims_col.ndim}')
print(f' mismo array agregando una dimensión a nivel filas: \n{more_dims_row} \n dimensiones: {more_dims_row.ndim}')

 array: [1 3 5], dimensiones: 1
 ***
 mismo array agregando una dimensión a nivel columnas: [[1 3 5]] , dimensiones: 2
 mismo array agregando una dimensión a nivel filas: 
[[1]
 [3]
 [5]] 
 dimensiones: 2


### eliminar dimensiones

usamos la función `np.squeeze()` para eliminar dimensiones de un array, tendrá como argumentos:
* el array

Lo que hace es comprimir al número de dimensiones "correcto" (elimina las dimensiones que estén vacías)


In [37]:
array_10 = np.array([10, 20, 30], ndmin= 10)
print(f' Este array tiene muchas dimensiones vacías: {array_10}        dims: {array_10.ndim}')

array_10_squeezed = np.squeeze(array_10)
print(f' Por medio de "squeeze()", las dimensiones vacías se han eliminado: {array_10_squeezed} , dims: {array_10_squeezed.ndim}')

 Este array tiene muchas dimensiones vacías: [[[[[[[[[[10 20 30]]]]]]]]]]        dims: 10
 Por medio de "squeeze()", las dimensiones vacías se han eliminado: [10 20 30] , dims: 1


hacer un tensor de 5 dimensiones, agregarle una dimensión en columnas, después eliminar las dimensiones que están vacías

In [44]:
tensor = np.array([
                    [
                        [
                            [ [1, 2, 3, 4], [6, 7, 8, 9], [10, 11, 12, 13] ],
                            [ [5, 14, 16, 17], [18, 19, 20, 21], [22, 23, 24, 25] ],
                            [ [26, 27, 28, 29], [30, 31, 32, 33], [34, 35, 36, 37]],
                            [ [38, 39, 40, 41], [42, 43, 44, 45], [46, 47, 48, 48] ],
                        ]
                    ]
                ], ndmin = 10)
tensor.ndim

10

In [45]:
#aumentar a 6 dimensiones en columnas
tensor= np.expand_dims(tensor, axis=1)
tensor.ndim

11

In [46]:
#eliminar dimensiones que están vacías
tensor = np.squeeze(tensor)
tensor.ndim

3

TypeError: Cannot interpret '5' as a data type