In [2]:
import numpy as np

usamos `array.dtype` para verificar de qué tipo de dato es
* Es posible usar `dtype = tipo` como un argumento a la hora de declarar un array

*los elementos tipo "float64" suelen usarse en redes neuronales / ML*

* Un **array de numpy** solo puede tener un tipo de dato
  * *no puede haber flotantes, enteros y strings en el mismo array*

In [3]:
array_vector = np.array([1, 2, 3, 4])


array_vector_float = np.array([1, 2, 3, 4], dtype= 'float64')

print(f' array predetemindado. tipo: {array_vector.dtype} \n array especificando float64: {array_vector_float}')

 array predetemindado. tipo: int64 
 array especificando float64: [1. 2. 3. 4.]


### cambiar el *dtype* de un array  que ya existe

usamos la función `array.astype(np.float64)` para cambiar un array a tipo flotante

Los elementos más comunes como argumento de `astype`: 
* `np.int64`    $\equiv$ `dtype = 'int64'`
* `np.float64`  $\equiv$ `dtype = 'float64'`
* `np.bool_`    $\equiv$ `dtype = 'bool`
* `np.string_`  $\equiv$ `dtype = 'string'`

cuando cambiamos un array que ya existe (con números) a booleano. El $0$ equivale a `False` y los demás números equivalen a `True`
* sin importar que sean números negativos



In [9]:
# convertir un entero a flotante
array_vector.astype(np.float64)

array([1., 2., 3., 4.])

In [6]:
# convertir un entero a booleano
array_vector_bool = np.array([-1, -2, 0, 4], dtype= bool)
array_vector_bool

array([ True,  True, False,  True])

In [13]:
# convertir un número flotante a un string
array_vector_string = array_vector_float.astype(np.string_)
array_vector_string 

array([b'1.0', b'2.0', b'3.0', b'4.0'], dtype='|S32')

In [15]:
#convertir un arrar con string de dígitos a enteros
array_vector_string_num = np.array(['1', '2', '3', '4'])
array_vector_string_num.astype(np.int8)

array([1, 2, 3, 4], dtype=int8)