# shape reshape : formas de un array

Hay dos funciones muy importantes para usar en los arrays `shape, reshape` 
* la forma de un array nos va a decir con qué estructura está trajando: (tamaño, manipular, ingresar)

### shape
 indica la forma del array usando el keyword `.shape`

In [1]:
import numpy as np

In [5]:
# definir un vector de número entre 1 y 10 con un largo de 5
a = np.array(np.linspace(1,10,5))
print(f' array de 5 elementos entre 1 y 10: {a} \n shape: {a.shape}')

 array de 5 elementos entre 1 y 10: [ 1.    3.25  5.5   7.75 10.  ] 
 shape: (5,)


In [17]:
# definir una matriz con ceros con una estructura de (3f ,2c)
b = np.array(np.zeros((3, 2)))
print(f' matriz (3,2) con 0s: \n{b} \n shape: {b.shape}')

 matriz (3,2) con 0s: 
[[0. 0.]
 [0. 0.]
 [0. 0.]] 
 shape: (3, 2)


### reshape()
 Cambia el *shape* que tenemos establecido en el array, tal que todos sus elementos puede acomodarse en el nuevo shape
 * el reshape debe mantener a todos los elementos del array, sin que haya más ó menos espacios

Existen dos métodos para hacer el reshape:
* (1) desde la variable que contiene el array, invocamos al `.reshape()` sus argumentos son: 
    * el "shape": las dimensiones compatibles con el array
    * `order = ` se ordenan los elementos según los paradigmas de `C, A, F` (no obligatorio)
     * `A` es el predeterminado del sistema (donde estamos trabando) puede ser *"F-C"*
     * `C` se ordenan según lo haría el lenguaje `C`
        * el lenguaje C ordena **por filas**: 
          * toma los elementos que quepan en una fila y los coloca ahí, después va a la siguiente fila y coloca los demás
     * `F` se ordenan según lo haría el lenguaje `Fortran`
        * el lenguaje Fortrand ordena los elementos **por columnas**:
          * de arriba hacia abajo va tomando los elementos y los va colocando, cuando se llena una columna empieza con el elemento que quede más arriba y continúa hacia abajo hasta llenar la nueva columna, hasta ordenar todos los números 

     así: `array.reshape(2,3, order = 'C')`

* (2) colocamos a la variable que contiene el array como uno de sus argumentos, de esta forma:
  * array
  * nuevo *shape* en una tupla (condimensiones compatibles con el array)
  * `order =` 

  así : `np.reshape(array, (2,3), order = 'F')`

#### ¿Cómo encontrar un shape compatible con el array? 
Dado un array con shape (2,3) podemos considerarlos como una multiplicación $2*3 =6$ 
 * por lo que un *shape* compatible podría ser uno que también de $=6$ como $1*6 = 6\space$  ò  $\space 3*2=6$
 * **conclusión**: hay que encontrar dos números que al multiplicarlos den igual al producto del shape $2*3$ 
    * los cuales serían $2*3 \space$ , $\space 1*6$ porque ambos dan como resultado $6$
   
**NOTA**: A la hora definir cómo se estarán ordenando los elementos, lo más recomendado es usar "C" ya que este lenguaje es la base de python. Al usar "A" podríamos perder el control de cómo se estarían ordenando los valores

In [56]:
# array con con números del 0 al 10 con 5 elementos
array = np.array(np.linspace(0,10,5))
print(f' array: {array} shape: {array.shape}')

#hacemos un reshape, pasandolo a vector columna
array_reshape_1 = array.reshape(5,1)                    # método uno
array_reshape_2 = np.reshape(array, (5, 1), order= 'F') # método dos 

 array: [ 0.   2.5  5.   7.5 10. ] shape: (5,)


In [55]:
print(f'\n reshape 1: \n {array_reshape_1} shape: {array_reshape_1.shape}')
print(f'\n reshape 2: \n {array_reshape_2} shape: {array_reshape_2.shape}')


 reshape 1: 
 [[ 0. ]
 [ 2.5]
 [ 5. ]
 [ 7.5]
 [10. ]] shape: (5, 1)

 reshape 2: 
 [[ 0. ]
 [ 2.5]
 [ 5. ]
 [ 7.5]
 [10. ]] shape: (5, 1)


practicando con reshape:

In [60]:
array_random = np.random.randint(1,10,(3,2))
array_random
print(f' array_random: \n{array_random} \n shape: {array_random.shape}')

 array_random: 
[[6 5]
 [1 1]
 [4 4]] 
 shape: (3, 2)


ordenar los elementos del array según "fortrand" ó "C"

In [67]:
array_random.reshape(2,3, order="F") #ordenar los elementos al estilo Fortrand

array([[6, 4, 1],
       [1, 5, 4]])

In [69]:
np.reshape(array_random, (2,3), "C") #ordenar los elementos al estilo C

array([[6, 5, 1],
       [1, 4, 4]])