# Creando arrays
Numpy nos da varios métodos muy eficientes para poder crear arrays desde 0


### np.arange( )
Este método de numpy nos permite generar arrays sin definir previamente una lista, sus argumentos son parecidos a los slices:
 * inicio del rango 
 * fin del rango
 * número de saltos entre cada uno de los números

 así : `np.arange(inicio, fin , saltos)` $\equiv$ `np.arange(0,10, 2)`

   * *NOTA:  al igual que en los slices, no se toma en cuenta el límite (el último número del array)*
      * *en este caso se están invocando números pares del 0 - 10 , a pesar formar parte el 10 en esta sucesión. No se colocará en el array*

In [1]:
import numpy as np

In [2]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### np.zeros( )
Nos permite definir estructura ó esquemas que consisten en una lista de 0's. expresados de manera predefinida como flotantes. Respecto a los argumentos podemos, definir:
* número de elementos. Puede especificarse con **un número** (columnas) ó **dos números** (filas, columnas) 
    * Si solo especificamos un número, este será equivalente al número de columnas, tal como un vector
        * así: `np.zeros(2)` R: *array ([0.,0.])*
    * Si especificamos la estructura como una matriz(filas, columnas) el número de elementos será el equivalente al número de filas
        * así: `np.zeros((2,5))` 
            * R: *array ([0.,0.],[0.,0.],[0.,0.],[0.,0.],[0.,0.])*
   


In [3]:
# un solo elemento (vector)
a = np.zeros(2)

# un elemento, pero definiéndolo como una tupla
b = np.zeros((2,))

print(f'a : {a} b: {b}')


a : [0. 0.] b: [0. 0.]


In [4]:
# dos elementos (filas, columnas), notar que no es lo mismo al definir al menos una columna
c = np.zeros((5)) # 5 ceros dispersos en columnas (vector)
d = np.zeros((5,1)) # 5 ceros dispersos en filas (matriz)
print(f' 5 ceros dispersos en columnas: {c} \n 5 ceros dispersos en filas: \n{d}')

 5 ceros dispersos en columnas: [0. 0. 0. 0. 0.] 
 5 ceros dispersos en filas: 
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


### np.ones( )
Es igual que `np.zeros()` pero con 1's

In [5]:
# un solo elemento (vector)
a = np.ones(10) #(columnas)

# dos elementos, definiéndolos como una tupla (matriz)
b = np.ones((3,10)) #(filas, columnas)

# tres elementos, definiendo en una tupla filas, columnas, repetisiones (tensor)
c = np.ones((3,4,5)) # número de matrices, filas, columnas
print(f'a : {a}\nb:\n  {b} \n c: \n {c}')

a : [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
b:
  [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] 
 c: 
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


### np.linspace( )

Permite generar un array definiendo como argumento:
* un inicio y un final
* el largo del array (si no se coloca esta argumento, se definirá un array de 50 elementos dentro del rango colocado)
* `dtype = ` definir el tipo `int, int16, int8, float, float16`

In [6]:
# array con elementos entre 0 y 1
array_linspace = np.linspace(0,1)
print(f' array entre 0 y 1: \n{array_linspace}\n shape: {array_linspace.shape}')

 array entre 0 y 1: 
[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]
 shape: (50,)


In [7]:
# array con elementos entre 1 y 100, con un largo de 5 elementos
array_linspace_5 = np.linspace(1,100,5)
print(f' array entre 1 y 100: {array_linspace_5}\n shape: {array_linspace_5.shape}')

 array entre 1 y 100: [  1.    25.75  50.5   75.25 100.  ]
 shape: (5,)


### np.eye( )
Podemos colocar unadiagonal de 1's en una matriz donde el resto son 0's, teniendo como argumento:
* el número de 1's que habrá en una matriz, por cada "1" habrá una fila


In [8]:
diagonal = np.eye(4)
diagonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### np.random.rand( )
Esta función la podemos usar para crear un array con números aleatorios dentro de un **rango (0,1)**, teniendo como argumento:
* para hacer un **vector**:
    * el número de elementos que tendrá el array
* haciendo una **matriz**:
    * podría especificarse este array como una matriz especificando filas y columnas (no obligatorio)
* haciendo un **tensor**:
    * indicar (número de matrices, ancho/columnas, alto/filas)

In [9]:
#un número aleatorio (scalar)
np.random.rand()

0.949851025601617

In [10]:
#lista de 4 números aleatorios (vector)
np.random.rand(4)

array([0.30556044, 0.8083437 , 0.70532865, 0.41568056])

In [11]:
#matriz de 3 filas, 5 columnas con números aleatorios
np.random.rand(3,4)

array([[0.54220385, 0.77511165, 0.94421338, 0.94488318],
       [0.03265739, 0.24729817, 0.33815804, 0.86150641],
       [0.60281661, 0.58498873, 0.31414528, 0.11012945]])

### np.random.randint( )
con esta función podemos crear un array de números enteros. Respecto a los argumentos:
* rango del número a elegir (inicio, final)
* número de elementos que tendrá el array
    * para hacer una matriz, este parámetro sería una tupla, indicando filas/columnas


In [12]:
# seleccionar un número en un rango de 3-10
a = np.random.randint(3,10)

# en un vector de 5 elementos, colocar números aleatorios entre 0 y 25
b = np.random.randint(0,25,5)

# en una matriz de  (3 filas, 4 columnas) colocar aleatroios entre 10 y 90
c = np.random.randint(10, 90, (3,4))

print(" *** enteros ***")
print(f' scalar: {a} \n vector: {b} \n matriz: \n{c}')

 *** enteros ***
 scalar: 8 
 vector: [11 19  2 24 19] 
 matriz: 
[[55 34 86 65]
 [17 69 48 51]
 [83 61 24 81]]


### np.arange( )

Esta función permite hacer un array con números continuos
* hace una lista de elementos con el rango especificado *sin contar el límite*. Estos son sus parámetros:

`np.arange([ start : stop : steps ], dtype = None, * , like = None)`

argumentos:
* slices
    * *start* : puede ser un entero (opcional)
    * *stop* : puede ser un entero
    * *steps* : entero (opcional)
* `dtype = ` especificar el tipo de elemento (np.int8, np.int16, float16 )
* `align = bool` puede ser `True` cuando un *obj* es un string separado por comas
* `copy = bool` copia del tipo de datos, hace una referencia a un objeto de tipo de datos incorporado



In [26]:
np.arange(5, dtype="int")

array([0, 1, 2, 3, 4])

In [27]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])