# Condiciones

Las condiciones nos permiten hacer consultas más específicas

A parte de usar los operadores `>, ==, % < ` para aplicar una condición, también es posible usar una función que en ciertos caso puede ser muy útil:

### np.where( )
Es una función que ayuda a construir condiciones, e indicar qué valores colocar si la condición se cumple y qué poner cuando no.

`np.where(`array condición , si se cumple , si no se cumple`)`

así:   `where = np.where(matriz > 50, 9999, 1111)`

In [102]:
# matriz de 3x3 con números aleatorios del 1 al 100
matriz = np.random.randint(1,100, (3,3))

# colocar 9999 cuando el valor es mayor a 50 y 1111 cuando es menor a 50
where = np.where(matriz > 50, 9999, 1111)

print(f' matriz original: \n {matriz} \n* * *\n condición "np.where": \n{where} ')

 matriz original: 
 [[ 3 54 60]
 [37 96 92]
 [28 11 94]] 
* * *
 condición "np.where": 
[[1111 9999 9999]
 [1111 9999 9999]
 [1111 1111 9999]] 


In [94]:
import numpy as np

In [6]:
# start , stop , numero de elementos
array = np.linspace(1,10,9)

# detectar los números que sean mayores a 5
mayor_5 = array > 5

print(f' array con 9 números del 1 al 10: {array}\n')
print(f' detectar los valores que sean mayores a 5: {mayor_5}')

 array con 9 números del 1 al 10: [ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]

 detectar los valores que sean mayores a 5: [False False False False  True  True  True  True  True]


extraer del array original los valores que cumplan la condición (> 5)

In [7]:
array[mayor_5]

array([ 5.5  ,  6.625,  7.75 ,  8.875, 10.   ])

### Múltiples condiciones

es posible colocar múltiples condiciones al concatenarlos con `&`(y) `|`(o) dependiendo de la nececidad
* al colocar `&` todas las condiciones deben de cumplirse para que sea `True`
* al colocar `|` una de las dos (ó más) condiciones deben de cumplirse para que sea `True`
  * si ambas condiciones se cumplen, también es válido

In [81]:
# condición buscar obtener números mayores a 3 o iguales a 1
lista_condiciones = list(array[(array >6)|(array ==1)])

# pasamos todo a enteros y nuevamente a flotantes (solo por práctica)
lista_int = [int(i) for i in lista_condiciones]

def flotantes(array):
    lista = []
    for i in array:
        lista.append(float(i))
    return lista

lista_float = flotantes(lista_int)
lista_float


[1.0, 7.0, 8.0, 9.0, 10.0]

En la lista de flotantes `lista_int`:
* (1) convertir la lista a un array
* (2) cambiar todos los valores mayores a 7 a 9999

In [80]:
array_int = np.array(lista_int) # (1)
array_int[array_int > 7] = 9999 # (2)
array_int

array([   1,    6,    7, 9999, 9999])

In [82]:
#mostrar solo los valores que son 9999
array_int[array_int == 9999]

array([9999, 9999])

práctica

In [74]:
array = np.linspace(1,10,10)

# del array, tomar el "1" y los valores mayores a 5
condicion = (array == 1) | (array > 5) 
condicion

array([ True, False, False, False, False,  True,  True,  True,  True,
        True])

el resultado es una lista mostrando dónde se cumple la condición y dónde no
* para obtener los valores que cumplen la condición, hay que ejecutar la condición dentro del array original

In [75]:
#ejecutar condición
array[condicion]

array([ 1.,  6.,  7.,  8.,  9., 10.])

In [76]:
# extraer de la lista el "1" y todos los pares
pares_o_uno = array[(array %2 == 0)| (array == 1)]
pares_o_uno

array([ 1.,  2.,  4.,  6.,  8., 10.])